version: '3'
services:
  garage-app:
    image: garage-management
    container_name: garage-management
    build:
      context: .
    ports:
      - "3500:3500"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app-network
    restart: always

  postgres:
    image: postgres:latest
    container_name: garage-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

networks:
  app-network:

volumes:
  pg_data:
